server:
  port: 8081
  servlet:
    context-path: /desarrollo
spring:
  application:
    name: snkrlab-ms-auth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AZURE_ISSUER_URI:https://login.microsoftonline.com/}
          tenant-id: ${AZURE_TENANT_ID:db9d1cc0-8c32-4341-bc72-c348daf096fb}